"""initial schema

Revision ID: 31e77be6b0e1
Revises:
Create Date: 2026-02-08 16:44:06.180922
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e77be6b0e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill",
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("bill_number", sa.String(length=50), nullable=False),
        sa.Column("congress", sa.Integer(), nullable=False),
        sa.Column(
            "bill_type",
            sa.Enum(
                "HR",
                "S",
                "HJRES",
                "SJRES",
                "HCONRES",
                "SCONRES",
                "HRES",
                "SRES",
                name="bill_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "Introduced",
                "In_Committee",
                "Reported_by_Committee",
                "Passed_House",
                "Passed_Senate",
                "Resolving_Differences",
                "To_President",
                "Became_Law",
                "Failed",
                "Vetoed",
                "Veto_Overridden",
                "Pocket_Vetoed",
                "Died_in_Committee",
                "Withdrawn",
                name="bill_status",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("short_title", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("introduced_date", sa.Date(), nullable=True),
        sa.Column("last_action_date", sa.Date(), nullable=True),
        sa.Column("last_action", sa.Text(), nullable=True),
        sa.Column("congress_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "congress >= 1 AND congress <= 200",
            name=op.f("ck_bill_ck_bill_congress_range"),
        ),
        sa.PrimaryKeyConstraint("bill_id", name=op.f("pk_bill")),
        sa.UniqueConstraint("congress", "bill_number", name="uq_bill_congress_number"),
    )
    op.create_index("idx_bill_congress", "bill", ["congress"], unique=False)
    op.create_index(
        "idx_bill_pending",
        "bill",
        ["status"],
        unique=False,
        postgresql_where="status NOT IN ('Became_Law', 'Failed', 'Vetoed', 'Died_in_Committee')",
    )
    op.create_index("idx_bill_status", "bill", ["status"], unique=False)
    op.create_table(
        "committee",
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.Column("committee_code", sa.String(length=20), nullable=False),
        sa.Column(
            "chamber", sa.Enum("House", "Senate", name="chamber"), nullable=False
        ),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("parent_committee_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_committee_id"],
            ["committee.committee_id"],
            name=op.f("fk_committee_parent_committee_id_committee"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("committee_id", name=op.f("pk_committee")),
        sa.UniqueConstraint("committee_code", name=op.f("uq_committee_committee_code")),
    )
    op.create_index("idx_committee_chamber", "committee", ["chamber"], unique=False)
    op.create_table(
        "data_correction",
        sa.Column("correction_id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("corrected_by", sa.String(length=100), nullable=False),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_by", sa.String(length=100), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("correction_id", name=op.f("pk_data_correction")),
    )
    op.create_index(
        "idx_correction_date", "data_correction", ["corrected_at"], unique=False
    )
    op.create_index(
        "idx_correction_record",
        "data_correction",
        ["table_name", "record_id"],
        unique=False,
    )
    op.create_index(
        "idx_correction_table", "data_correction", ["table_name"], unique=False
    )
    op.create_table(
        "data_ingestion_log",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_created", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_data_ingestion_log")),
    )
    op.create_index(
        "idx_ingestion_source", "data_ingestion_log", ["source"], unique=False
    )
    op.create_index(
        "idx_ingestion_started", "data_ingestion_log", ["started_at"], unique=False
    )
    op.create_index(
        "idx_ingestion_status", "data_ingestion_log", ["status"], unique=False
    )
    op.create_table(
        "legislator",
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.Column("bioguide_id", sa.String(length=20), nullable=False),
        sa.Column("thomas_id", sa.String(length=20), nullable=True),
        sa.Column("govtrack_id", sa.Integer(), nullable=True),
        sa.Column("opensecrets_id", sa.String(length=20), nullable=True),
        sa.Column("fec_id", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("suffix", sa.String(length=20), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column(
            "party",
            sa.Enum(
                "Democrat",
                "Republican",
                "Independent",
                "Libertarian",
                "Green",
                "Other",
                name="political_party",
            ),
            nullable=True,
        ),
        sa.Column("state", sa.CHAR(length=2), nullable=True),
        sa.Column("district", sa.String(length=10), nullable=True),
        sa.Column(
            "current_chamber", sa.Enum("House", "Senate", name="chamber"), nullable=True
        ),
        sa.Column("is_current_member", sa.Boolean(), nullable=False),
        sa.Column("first_served", sa.Date(), nullable=True),
        sa.Column("last_served", sa.Date(), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("official_website", sa.String(length=500), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("death_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.CHAR(length=1), nullable=True),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("legislator_id", name=op.f("pk_legislator")),
        sa.UniqueConstraint("bioguide_id", name=op.f("uq_legislator_bioguide_id")),
    )
    op.create_index(
        "idx_legislator_current",
        "legislator",
        ["is_current_member"],
        unique=False,
        postgresql_where="is_current_member = TRUE",
    )
    op.create_index("idx_legislator_party", "legislator", ["party"], unique=False)
    op.create_index("idx_legislator_state", "legislator", ["state"], unique=False)
    op.create_table(
        "section_group",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("group_type", sa.String(length=50), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_positive_law", sa.Boolean(), nullable=False),
        sa.Column("positive_law_date", sa.Date(), nullable=True),
        sa.Column("positive_law_citation", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["section_group.group_id"],
            name=op.f("fk_section_group_parent_id_section_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_section_group")),
        sa.UniqueConstraint(
            "parent_id", "group_type", "number", name="uq_section_group_child"
        ),
    )
    op.create_index(
        "idx_section_group_parent", "section_group", ["parent_id"], unique=False
    )
    op.create_index(
        "idx_section_group_sort",
        "section_group",
        ["parent_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        "idx_section_group_type", "section_group", ["group_type"], unique=False
    )
    op.create_table(
        "amendment",
        sa.Column("amendment_id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("amendment_number", sa.String(length=50), nullable=False),
        sa.Column(
            "chamber", sa.Enum("House", "Senate", name="chamber"), nullable=False
        ),
        sa.Column("congress", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sponsor_id", sa.Integer(), nullable=True),
        sa.Column("submitted_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.bill_id"],
            name=op.f("fk_amendment_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["legislator.legislator_id"],
            name=op.f("fk_amendment_sponsor_id_legislator"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("amendment_id", name=op.f("pk_amendment")),
        sa.UniqueConstraint(
            "congress", "amendment_number", name="uq_amendment_congress_number"
        ),
    )
    op.create_index("idx_amendment_bill", "amendment", ["bill_id"], unique=False)
    op.create_index("idx_amendment_congress", "amendment", ["congress"], unique=False)
    op.create_table(
        "bill_committee_assignment",
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.Column("referral_date", sa.Date(), nullable=True),
        sa.Column("discharge_date", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.bill_id"],
            name=op.f("fk_bill_committee_assignment_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.committee_id"],
            name=op.f("fk_bill_committee_assignment_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "assignment_id", name=op.f("pk_bill_committee_assignment")
        ),
        sa.UniqueConstraint("bill_id", "committee_id", name="uq_bill_committee"),
    )
    op.create_index(
        "idx_assignment_bill", "bill_committee_assignment", ["bill_id"], unique=False
    )
    op.create_index(
        "idx_assignment_committee",
        "bill_committee_assignment",
        ["committee_id"],
        unique=False,
    )
    op.create_table(
        "legislator_term",
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.Column(
            "chamber", sa.Enum("House", "Senate", name="chamber"), nullable=False
        ),
        sa.Column("state", sa.CHAR(length=2), nullable=False),
        sa.Column("district", sa.String(length=10), nullable=True),
        sa.Column(
            "party",
            sa.Enum(
                "Democrat",
                "Republican",
                "Independent",
                "Libertarian",
                "Green",
                "Other",
                name="political_party",
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("congress", sa.Integer(), nullable=True),
        sa.Column("class_number", sa.Integer(), nullable=True),
        sa.Column("state_rank", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislator.legislator_id"],
            name=op.f("fk_legislator_term_legislator_id_legislator"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("term_id", name=op.f("pk_legislator_term")),
    )
    op.create_index("idx_term_congress", "legislator_term", ["congress"], unique=False)
    op.create_index(
        "idx_term_dates", "legislator_term", ["start_date", "end_date"], unique=False
    )
    op.create_index(
        "idx_term_legislator", "legislator_term", ["legislator_id"], unique=False
    )
    op.create_table(
        "public_law",
        sa.Column("law_id", sa.Integer(), nullable=False),
        sa.Column("law_number", sa.String(length=20), nullable=False),
        sa.Column("congress", sa.Integer(), nullable=False),
        sa.Column(
            "law_type", sa.Enum("Public", "Private", name="law_type"), nullable=False
        ),
        sa.Column("popular_name", sa.String(length=500), nullable=True),
        sa.Column("official_title", sa.Text(), nullable=True),
        sa.Column("short_title", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("bill_number", sa.String(length=50), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.Column("introduced_date", sa.Date(), nullable=True),
        sa.Column("house_passed_date", sa.Date(), nullable=True),
        sa.Column("senate_passed_date", sa.Date(), nullable=True),
        sa.Column("presented_to_president_date", sa.Date(), nullable=True),
        sa.Column("enacted_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("president", sa.String(length=100), nullable=True),
        sa.Column("presidential_action", sa.String(length=50), nullable=True),
        sa.Column("veto_date", sa.Date(), nullable=True),
        sa.Column("veto_override_date", sa.Date(), nullable=True),
        sa.Column("sections_affected", sa.Integer(), nullable=False),
        sa.Column("sections_added", sa.Integer(), nullable=False),
        sa.Column("sections_modified", sa.Integer(), nullable=False),
        sa.Column("sections_repealed", sa.Integer(), nullable=False),
        sa.Column("govinfo_url", sa.String(length=500), nullable=True),
        sa.Column("congress_url", sa.String(length=500), nullable=True),
        sa.Column("statutes_at_large_citation", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "congress >= 1 AND congress <= 200",
            name=op.f("ck_public_law_ck_public_law_congress_range"),
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.bill_id"],
            name=op.f("fk_public_law_bill_id_bill"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("law_id", name=op.f("pk_public_law")),
        sa.UniqueConstraint("congress", "law_number", name="uq_law_congress_number"),
    )
    op.create_index("idx_law_congress", "public_law", ["congress"], unique=False)
    op.create_index("idx_law_effective", "public_law", ["effective_date"], unique=False)
    op.create_index("idx_law_enacted", "public_law", ["enacted_date"], unique=False)
    op.create_index(
        "idx_law_number", "public_law", ["congress", "law_number"], unique=False
    )
    op.create_index(
        "idx_law_popular_name", "public_law", ["popular_name"], unique=False
    )
    op.create_index("idx_law_president", "public_law", ["president"], unique=False)
    op.create_table(
        "parsing_session",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("law_id", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("Human_Plus_LLM", "LLM", "RegEx", name="parsing_mode"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "In_Progress",
                "Completed",
                "Failed",
                "Escalated",
                name="parsing_session_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_session_id", sa.Integer(), nullable=True),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("escalated_by", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["public_law.law_id"],
            name=op.f("fk_parsing_session_law_id_public_law"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_session_id"],
            ["parsing_session.session_id"],
            name=op.f("fk_parsing_session_parent_session_id_parsing_session"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_parsing_session")),
    )
    op.create_index(
        "idx_parsing_session_law", "parsing_session", ["law_id"], unique=False
    )
    op.create_index(
        "idx_parsing_session_mode", "parsing_session", ["mode"], unique=False
    )
    op.create_index(
        "idx_parsing_session_started", "parsing_session", ["started_at"], unique=False
    )
    op.create_index(
        "idx_parsing_session_status", "parsing_session", ["status"], unique=False
    )
    op.create_table(
        "sponsorship",
        sa.Column("sponsorship_id", sa.Integer(), nullable=False),
        sa.Column("law_id", sa.Integer(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("Sponsor", "Cosponsor", name="sponsorship_role"),
            nullable=False,
        ),
        sa.Column("sponsorship_date", sa.Date(), nullable=True),
        sa.Column("withdrawn_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(law_id IS NOT NULL AND bill_id IS NULL) OR (law_id IS NULL AND bill_id IS NOT NULL)",
            name=op.f("ck_sponsorship_ck_sponsorship_law_or_bill"),
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.bill_id"],
            name=op.f("fk_sponsorship_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["public_law.law_id"],
            name=op.f("fk_sponsorship_law_id_public_law"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislator.legislator_id"],
            name=op.f("fk_sponsorship_legislator_id_legislator"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sponsorship_id", name=op.f("pk_sponsorship")),
    )
    op.create_index("idx_sponsorship_bill", "sponsorship", ["bill_id"], unique=False)
    op.create_index("idx_sponsorship_law", "sponsorship", ["law_id"], unique=False)
    op.create_index(
        "idx_sponsorship_legislator", "sponsorship", ["legislator_id"], unique=False
    )
    op.create_index(
        "idx_sponsorship_sponsor",
        "sponsorship",
        ["law_id", "role"],
        unique=False,
        postgresql_where="role = 'Sponsor'",
    )
    op.create_table(
        "us_code_section",
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("title_number", sa.Integer(), nullable=False),
        sa.Column("section_number", sa.String(length=50), nullable=False),
        sa.Column("heading", sa.Text(), nullable=False),
        sa.Column("full_citation", sa.String(length=200), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("enacted_date", sa.Date(), nullable=True),
        sa.Column("last_modified_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("is_positive_law", sa.Boolean(), nullable=False),
        sa.Column("title_positive_law_date", sa.Date(), nullable=True),
        sa.Column("statutes_at_large_citation", sa.String(length=200), nullable=True),
        sa.Column("is_repealed", sa.Boolean(), nullable=False),
        sa.Column("repealed_date", sa.Date(), nullable=True),
        sa.Column("repealed_by_law_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "normalized_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "normalized_provisions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(is_repealed = FALSE AND repealed_date IS NULL) OR (is_repealed = TRUE AND repealed_date IS NOT NULL)",
            name=op.f("ck_us_code_section_ck_us_code_section_repealed_consistency"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["section_group.group_id"],
            name=op.f("fk_us_code_section_group_id_section_group"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["repealed_by_law_id"],
            ["public_law.law_id"],
            name=op.f("fk_us_code_section_repealed_by_law_id_public_law"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("section_id", name=op.f("pk_us_code_section")),
        sa.UniqueConstraint(
            "title_number", "section_number", name="uq_section_title_number"
        ),
    )
    op.create_index(
        "idx_section_active",
        "us_code_section",
        ["is_repealed"],
        unique=False,
        postgresql_where="is_repealed = FALSE",
    )
    op.create_index(
        "idx_section_citation", "us_code_section", ["full_citation"], unique=False
    )
    op.create_index("idx_section_group", "us_code_section", ["group_id"], unique=False)
    op.create_index(
        "idx_section_number",
        "us_code_section",
        ["title_number", "section_number"],
        unique=False,
    )
    op.create_index(
        "idx_section_sort", "us_code_section", ["group_id", "sort_order"], unique=False
    )
    op.create_index(
        "idx_section_title_number", "us_code_section", ["title_number"], unique=False
    )
    op.create_table(
        "vote",
        sa.Column("vote_id", sa.Integer(), nullable=False),
        sa.Column("law_id", sa.Integer(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.Column(
            "chamber", sa.Enum("House", "Senate", name="chamber"), nullable=False
        ),
        sa.Column("vote_date", sa.Date(), nullable=False),
        sa.Column("vote_number", sa.Integer(), nullable=True),
        sa.Column("congress", sa.Integer(), nullable=False),
        sa.Column("session", sa.Integer(), nullable=True),
        sa.Column("question", sa.String(length=500), nullable=True),
        sa.Column("result", sa.String(length=100), nullable=True),
        sa.Column("yeas", sa.Integer(), nullable=False),
        sa.Column("nays", sa.Integer(), nullable=False),
        sa.Column("present", sa.Integer(), nullable=False),
        sa.Column("not_voting", sa.Integer(), nullable=False),
        sa.Column("required_majority", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.bill_id"],
            name=op.f("fk_vote_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["public_law.law_id"],
            name=op.f("fk_vote_law_id_public_law"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("vote_id", name=op.f("pk_vote")),
    )
    op.create_index("idx_vote_bill", "vote", ["bill_id"], unique=False)
    op.create_index("idx_vote_chamber", "vote", ["chamber"], unique=False)
    op.create_index("idx_vote_date", "vote", ["vote_date"], unique=False)
    op.create_index("idx_vote_law", "vote", ["law_id"], unique=False)
    op.create_table(
        "individual_vote",
        sa.Column("individual_vote_id", sa.Integer(), nullable=False),
        sa.Column("vote_id", sa.Integer(), nullable=False),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.Column(
            "vote_cast",
            sa.Enum(
                "Yea",
                "Nay",
                "Present",
                "Not_Voting",
                "Paired_Yea",
                "Paired_Nay",
                name="vote_type",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislator.legislator_id"],
            name=op.f("fk_individual_vote_legislator_id_legislator"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vote_id"],
            ["vote.vote_id"],
            name=op.f("fk_individual_vote_vote_id_vote"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("individual_vote_id", name=op.f("pk_individual_vote")),
        sa.UniqueConstraint(
            "vote_id", "legislator_id", name="uq_individual_vote_vote_legislator"
        ),
    )
    op.create_index(
        "idx_individual_vote_legislator",
        "individual_vote",
        ["legislator_id"],
        unique=False,
    )
    op.create_index(
        "idx_individual_vote_vote", "individual_vote", ["vote_id"], unique=False
    )
    op.create_table(
        "ingestion_report",
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("law_id", sa.Integer(), nullable=False),
        sa.Column("total_text_length", sa.Integer(), nullable=False),
        sa.Column("claimed_text_length", sa.Integer(), nullable=False),
        sa.Column("coverage_percentage", sa.Float(), nullable=False),
        sa.Column("unclaimed_flagged_count", sa.Integer(), nullable=False),
        sa.Column("unclaimed_ignored_count", sa.Integer(), nullable=False),
        sa.Column("total_amendments", sa.Integer(), nullable=False),
        sa.Column("high_confidence_count", sa.Integer(), nullable=False),
        sa.Column("needs_review_count", sa.Integer(), nullable=False),
        sa.Column("avg_confidence", sa.Float(), nullable=False),
        sa.Column(
            "amendments_by_type", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "amendments_by_pattern",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("auto_approve_eligible", sa.Boolean(), nullable=False),
        sa.Column("escalation_recommended", sa.Boolean(), nullable=False),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("govinfo_amendment_count", sa.Integer(), nullable=True),
        sa.Column("amendment_count_mismatch", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "avg_confidence >= 0 AND avg_confidence <= 1",
            name=op.f("ck_ingestion_report_ck_ingestion_report_confidence_range"),
        ),
        sa.CheckConstraint(
            "coverage_percentage >= 0 AND coverage_percentage <= 100",
            name=op.f("ck_ingestion_report_ck_ingestion_report_coverage_range"),
        ),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["public_law.law_id"],
            name=op.f("fk_ingestion_report_law_id_public_law"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["parsing_session.session_id"],
            name=op.f("fk_ingestion_report_session_id_parsing_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_ingestion_report")),
        sa.UniqueConstraint("session_id", name=op.f("uq_ingestion_report_session_id")),
    )
    op.create_index(
        "idx_ingestion_report_coverage",
        "ingestion_report",
        ["coverage_percentage"],
        unique=False,
    )
    op.create_index(
        "idx_ingestion_report_eligible",
        "ingestion_report",
        ["auto_approve_eligible"],
        unique=False,
    )
    op.create_index(
        "idx_ingestion_report_law", "ingestion_report", ["law_id"], unique=False
    )
    op.create_table(
        "law_change",
        sa.Column("change_id", sa.Integer(), nullable=False),
        sa.Column("law_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum(
                "Add",
                "Delete",
                "Modify",
                "Repeal",
                "Redesignate",
                "Transfer",
                name="change_type",
            ),
            nullable=False,
        ),
        sa.Column("old_text", sa.Text(), nullable=True),
        sa.Column("new_text", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("subsection_path", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["public_law.law_id"],
            name=op.f("fk_law_change_law_id_public_law"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["us_code_section.section_id"],
            name=op.f("fk_law_change_section_id_us_code_section"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_law_change")),
    )
    op.create_index("idx_change_law", "law_change", ["law_id"], unique=False)
    op.create_index(
        "idx_change_law_section", "law_change", ["law_id", "section_id"], unique=False
    )
    op.create_index("idx_change_section", "law_change", ["section_id"], unique=False)
    op.create_table(
        "parsed_amendment_record",
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("pattern_name", sa.String(length=100), nullable=False),
        sa.Column("pattern_type", sa.String(length=50), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum(
                "Add",
                "Delete",
                "Modify",
                "Repeal",
                "Redesignate",
                "Transfer",
                name="change_type",
            ),
            nullable=False,
        ),
        sa.Column("target_title", sa.Integer(), nullable=True),
        sa.Column("target_section", sa.String(length=50), nullable=True),
        sa.Column("target_subsection_path", sa.String(length=100), nullable=True),
        sa.Column("old_text", sa.Text(), nullable=True),
        sa.Column("new_text", sa.Text(), nullable=True),
        sa.Column("start_pos", sa.Integer(), nullable=False),
        sa.Column("end_pos", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "Pending",
                "Approved",
                "Rejected",
                "Corrected",
                name="amendment_review_status",
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("corrected_pattern_name", sa.String(length=100), nullable=True),
        sa.Column("corrected_section", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f(
                "ck_parsed_amendment_record_ck_parsed_amendment_confidence_range"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["parsing_session.session_id"],
            name=op.f("fk_parsed_amendment_record_session_id_parsing_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("record_id", name=op.f("pk_parsed_amendment_record")),
    )
    op.create_index(
        "idx_parsed_amendment_needs_review",
        "parsed_amendment_record",
        ["needs_review"],
        unique=False,
    )
    op.create_index(
        "idx_parsed_amendment_pattern",
        "parsed_amendment_record",
        ["pattern_name"],
        unique=False,
    )
    op.create_index(
        "idx_parsed_amendment_review",
        "parsed_amendment_record",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        "idx_parsed_amendment_session",
        "parsed_amendment_record",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "idx_parsed_amendment_target",
        "parsed_amendment_record",
        ["target_title", "target_section"],
        unique=False,
    )
    op.create_table(
        "parsing_verification",
        sa.Column("verification_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("verified_by", sa.String(length=100), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "Manual_Review",
                "Automated_Comparison",
                "Third_Party_Audit",
                name="verification_method",
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum(
                "Passed", "Failed", "Passed_With_Issues", name="verification_result"
            ),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Free-form notes: methodology, issues found, coverage gaps, etc.",
        ),
        sa.Column(
            "issues_found", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["parsing_session.session_id"],
            name=op.f("fk_parsing_verification_session_id_parsing_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "verification_id", name=op.f("pk_parsing_verification")
        ),
    )
    op.create_index(
        "idx_parsing_verification_result",
        "parsing_verification",
        ["result"],
        unique=False,
    )
    op.create_index(
        "idx_parsing_verification_session",
        "parsing_verification",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "idx_parsing_verification_verified_at",
        "parsing_verification",
        ["verified_at"],
        unique=False,
    )
    op.create_table(
        "pattern_discovery",
        sa.Column("discovery_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("unmatched_text", sa.Text(), nullable=False),
        sa.Column("detected_keywords", sa.Text(), nullable=True),
        sa.Column("context_text", sa.Text(), nullable=True),
        sa.Column("start_pos", sa.Integer(), nullable=False),
        sa.Column("end_pos", sa.Integer(), nullable=False),
        sa.Column("suggested_pattern_name", sa.String(length=100), nullable=True),
        sa.Column("suggested_pattern_regex", sa.Text(), nullable=True),
        sa.Column("suggested_pattern_type", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "New",
                "Under_Review",
                "Promoted",
                "Rejected",
                name="pattern_discovery_status",
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("promoted_pattern_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["parsing_session.session_id"],
            name=op.f("fk_pattern_discovery_session_id_parsing_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("discovery_id", name=op.f("pk_pattern_discovery")),
    )
    op.create_index(
        "idx_pattern_discovery_session",
        "pattern_discovery",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "idx_pattern_discovery_status", "pattern_discovery", ["status"], unique=False
    )
    op.create_table(
        "proposed_change",
        sa.Column("change_id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "Add",
                "Delete",
                "Modify",
                "Repeal",
                "Redesignate",
                "Transfer",
                name="change_type",
            ),
            nullable=False,
        ),
        sa.Column("old_text", sa.Text(), nullable=True),
        sa.Column("new_text", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("subsection_path", sa.String(length=100), nullable=True),
        sa.Column("likelihood_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "likelihood_score IS NULL OR (likelihood_score >= 0 AND likelihood_score <= 1)",
            name=op.f("ck_proposed_change_ck_proposed_change_likelihood_range"),
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.bill_id"],
            name=op.f("fk_proposed_change_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["us_code_section.section_id"],
            name=op.f("fk_proposed_change_section_id_us_code_section"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_proposed_change")),
    )
    op.create_index(
        "idx_proposed_change_bill", "proposed_change", ["bill_id"], unique=False
    )
    op.create_index(
        "idx_proposed_change_section", "proposed_change", ["section_id"], unique=False
    )
    op.create_table(
        "section_history",
        sa.Column("history_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("law_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("heading", sa.String(length=500), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("superseded_date", sa.Date(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "superseded_date IS NULL OR superseded_date > effective_date",
            name=op.f("ck_section_history_ck_section_history_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["public_law.law_id"],
            name=op.f("fk_section_history_law_id_public_law"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["us_code_section.section_id"],
            name=op.f("fk_section_history_section_id_us_code_section"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("history_id", name=op.f("pk_section_history")),
        sa.UniqueConstraint(
            "section_id", "version_number", name="uq_section_history_version"
        ),
    )
    op.create_index("idx_history_law", "section_history", ["law_id"], unique=False)
    op.create_index(
        "idx_history_section", "section_history", ["section_id"], unique=False
    )
    op.create_index(
        "idx_history_section_date",
        "section_history",
        ["section_id", "effective_date"],
        unique=False,
    )
    op.create_index(
        "idx_history_version",
        "section_history",
        ["section_id", "version_number"],
        unique=False,
    )
    op.create_table(
        "section_reference",
        sa.Column("reference_id", sa.Integer(), nullable=False),
        sa.Column("source_section_id", sa.Integer(), nullable=False),
        sa.Column("target_section_id", sa.Integer(), nullable=False),
        sa.Column(
            "reference_type",
            sa.Enum(
                "Explicit_Citation",
                "Cross_Reference",
                "Subject_To",
                "Conditional",
                "Exception",
                "Incorporation",
                name="reference_type",
            ),
            nullable=False,
        ),
        sa.Column("source_subsection_path", sa.String(length=100), nullable=True),
        sa.Column("target_subsection_path", sa.String(length=100), nullable=True),
        sa.Column("reference_text", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "source_section_id != target_section_id",
            name=op.f("ck_section_reference_ck_section_reference_no_self_ref"),
        ),
        sa.ForeignKeyConstraint(
            ["source_section_id"],
            ["us_code_section.section_id"],
            name=op.f("fk_section_reference_source_section_id_us_code_section"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_section_id"],
            ["us_code_section.section_id"],
            name=op.f("fk_section_reference_target_section_id_us_code_section"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reference_id", name=op.f("pk_section_reference")),
        sa.UniqueConstraint(
            "source_section_id",
            "target_section_id",
            "reference_type",
            "source_subsection_path",
            name="uq_section_reference",
        ),
    )
    op.create_index(
        "idx_ref_source", "section_reference", ["source_section_id"], unique=False
    )
    op.create_index(
        "idx_ref_target", "section_reference", ["target_section_id"], unique=False
    )
    op.create_index(
        "idx_ref_type", "section_reference", ["reference_type"], unique=False
    )
    op.create_table(
        "us_code_line",
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("parent_line_id", sa.Integer(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("is_header", sa.Boolean(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("subsection_path", sa.String(length=100), nullable=True),
        sa.Column("depth_level", sa.Integer(), nullable=False),
        sa.Column("created_by_law_id", sa.Integer(), nullable=True),
        sa.Column("last_modified_by_law_id", sa.Integer(), nullable=True),
        sa.Column("codified_by_law_id", sa.Integer(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("codification_date", sa.Date(), nullable=True),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "depth_level >= 0",
            name=op.f("ck_us_code_line_ck_us_code_line_depth_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["codified_by_law_id"],
            ["public_law.law_id"],
            name=op.f("fk_us_code_line_codified_by_law_id_public_law"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_law_id"],
            ["public_law.law_id"],
            name=op.f("fk_us_code_line_created_by_law_id_public_law"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by_law_id"],
            ["public_law.law_id"],
            name=op.f("fk_us_code_line_last_modified_by_law_id_public_law"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_line_id"],
            ["us_code_line.line_id"],
            name=op.f("fk_us_code_line_parent_line_id_us_code_line"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["us_code_section.section_id"],
            name=op.f("fk_us_code_line_section_id_us_code_section"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("line_id", name=op.f("pk_us_code_line")),
        sa.UniqueConstraint("section_id", "line_number", name="uq_line_section_number"),
    )
    op.create_index(
        "idx_line_codified_by", "us_code_line", ["codified_by_law_id"], unique=False
    )
    op.create_index(
        "idx_line_created_by", "us_code_line", ["created_by_law_id"], unique=False
    )
    op.create_index(
        "idx_line_current",
        "us_code_line",
        ["section_id", "is_current"],
        unique=False,
        postgresql_where="is_current = TRUE",
    )
    op.create_index(
        "idx_line_depth", "us_code_line", ["section_id", "depth_level"], unique=False
    )
    op.create_index("idx_line_hash", "us_code_line", ["text_hash"], unique=False)
    op.create_index(
        "idx_line_modified_by",
        "us_code_line",
        ["last_modified_by_law_id"],
        unique=False,
    )
    op.create_index("idx_line_parent", "us_code_line", ["parent_line_id"], unique=False)
    op.create_index("idx_line_section", "us_code_line", ["section_id"], unique=False)
    op.create_index(
        "idx_line_section_order",
        "us_code_line",
        ["section_id", "line_number"],
        unique=False,
    )
    op.create_table(
        "line_history",
        sa.Column("line_history_id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("subsection_path", sa.String(length=100), nullable=True),
        sa.Column("modified_by_law_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("superseded_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "superseded_date IS NULL OR superseded_date > effective_date",
            name=op.f("ck_line_history_ck_line_history_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["us_code_line.line_id"],
            name=op.f("fk_line_history_line_id_us_code_line"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_law_id"],
            ["public_law.law_id"],
            name=op.f("fk_line_history_modified_by_law_id_public_law"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("line_history_id", name=op.f("pk_line_history")),
        sa.UniqueConstraint(
            "line_id", "version_number", name="uq_line_history_version"
        ),
    )
    op.create_index(
        "idx_line_history_law", "line_history", ["modified_by_law_id"], unique=False
    )
    op.create_index("idx_line_history_line", "line_history", ["line_id"], unique=False)
    op.create_index(
        "idx_line_history_line_date",
        "line_history",
        ["line_id", "effective_date"],
        unique=False,
    )
    op.create_index(
        "idx_line_history_version",
        "line_history",
        ["line_id", "version_number"],
        unique=False,
    )
    op.create_table(
        "text_span",
        sa.Column("span_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("start_pos", sa.Integer(), nullable=False),
        sa.Column("end_pos", sa.Integer(), nullable=False),
        sa.Column(
            "span_type",
            sa.Enum(
                "Claimed", "Unclaimed_Flagged", "Unclaimed_Ignored", name="span_type"
            ),
            nullable=False,
        ),
        sa.Column("amendment_record_id", sa.Integer(), nullable=True),
        sa.Column("pattern_name", sa.String(length=100), nullable=True),
        sa.Column("detected_keywords", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(span_type = 'Claimed' AND pattern_name IS NOT NULL) OR (span_type != 'Claimed')",
            name=op.f("ck_text_span_ck_text_span_claimed_has_pattern"),
        ),
        sa.CheckConstraint(
            "end_pos > start_pos", name=op.f("ck_text_span_ck_text_span_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["amendment_record_id"],
            ["parsed_amendment_record.record_id"],
            name=op.f("fk_text_span_amendment_record_id_parsed_amendment_record"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["parsing_session.session_id"],
            name=op.f("fk_text_span_session_id_parsing_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("span_id", name=op.f("pk_text_span")),
    )
    op.create_index(
        "idx_text_span_positions",
        "text_span",
        ["session_id", "start_pos", "end_pos"],
        unique=False,
    )
    op.create_index("idx_text_span_session", "text_span", ["session_id"], unique=False)
    op.create_index("idx_text_span_type", "text_span", ["span_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_text_span_type", table_name="text_span")
    op.drop_index("idx_text_span_session", table_name="text_span")
    op.drop_index("idx_text_span_positions", table_name="text_span")
    op.drop_table("text_span")
    op.drop_index("idx_line_history_version", table_name="line_history")
    op.drop_index("idx_line_history_line_date", table_name="line_history")
    op.drop_index("idx_line_history_line", table_name="line_history")
    op.drop_index("idx_line_history_law", table_name="line_history")
    op.drop_table("line_history")
    op.drop_index("idx_line_section_order", table_name="us_code_line")
    op.drop_index("idx_line_section", table_name="us_code_line")
    op.drop_index("idx_line_parent", table_name="us_code_line")
    op.drop_index("idx_line_modified_by", table_name="us_code_line")
    op.drop_index("idx_line_hash", table_name="us_code_line")
    op.drop_index("idx_line_depth", table_name="us_code_line")
    op.drop_index(
        "idx_line_current",
        table_name="us_code_line",
        postgresql_where="is_current = TRUE",
    )
    op.drop_index("idx_line_created_by", table_name="us_code_line")
    op.drop_index("idx_line_codified_by", table_name="us_code_line")
    op.drop_table("us_code_line")
    op.drop_index("idx_ref_type", table_name="section_reference")
    op.drop_index("idx_ref_target", table_name="section_reference")
    op.drop_index("idx_ref_source", table_name="section_reference")
    op.drop_table("section_reference")
    op.drop_index("idx_history_version", table_name="section_history")
    op.drop_index("idx_history_section_date", table_name="section_history")
    op.drop_index("idx_history_section", table_name="section_history")
    op.drop_index("idx_history_law", table_name="section_history")
    op.drop_table("section_history")
    op.drop_index("idx_proposed_change_section", table_name="proposed_change")
    op.drop_index("idx_proposed_change_bill", table_name="proposed_change")
    op.drop_table("proposed_change")
    op.drop_index("idx_pattern_discovery_status", table_name="pattern_discovery")
    op.drop_index("idx_pattern_discovery_session", table_name="pattern_discovery")
    op.drop_table("pattern_discovery")
    op.drop_index(
        "idx_parsing_verification_verified_at", table_name="parsing_verification"
    )
    op.drop_index("idx_parsing_verification_session", table_name="parsing_verification")
    op.drop_index("idx_parsing_verification_result", table_name="parsing_verification")
    op.drop_table("parsing_verification")
    op.drop_index("idx_parsed_amendment_target", table_name="parsed_amendment_record")
    op.drop_index("idx_parsed_amendment_session", table_name="parsed_amendment_record")
    op.drop_index("idx_parsed_amendment_review", table_name="parsed_amendment_record")
    op.drop_index("idx_parsed_amendment_pattern", table_name="parsed_amendment_record")
    op.drop_index(
        "idx_parsed_amendment_needs_review", table_name="parsed_amendment_record"
    )
    op.drop_table("parsed_amendment_record")
    op.drop_index("idx_change_section", table_name="law_change")
    op.drop_index("idx_change_law_section", table_name="law_change")
    op.drop_index("idx_change_law", table_name="law_change")
    op.drop_table("law_change")
    op.drop_index("idx_ingestion_report_law", table_name="ingestion_report")
    op.drop_index("idx_ingestion_report_eligible", table_name="ingestion_report")
    op.drop_index("idx_ingestion_report_coverage", table_name="ingestion_report")
    op.drop_table("ingestion_report")
    op.drop_index("idx_individual_vote_vote", table_name="individual_vote")
    op.drop_index("idx_individual_vote_legislator", table_name="individual_vote")
    op.drop_table("individual_vote")
    op.drop_index("idx_vote_law", table_name="vote")
    op.drop_index("idx_vote_date", table_name="vote")
    op.drop_index("idx_vote_chamber", table_name="vote")
    op.drop_index("idx_vote_bill", table_name="vote")
    op.drop_table("vote")
    op.drop_index("idx_section_title_number", table_name="us_code_section")
    op.drop_index("idx_section_sort", table_name="us_code_section")
    op.drop_index("idx_section_number", table_name="us_code_section")
    op.drop_index("idx_section_group", table_name="us_code_section")
    op.drop_index("idx_section_citation", table_name="us_code_section")
    op.drop_index(
        "idx_section_active",
        table_name="us_code_section",
        postgresql_where="is_repealed = FALSE",
    )
    op.drop_table("us_code_section")
    op.drop_index(
        "idx_sponsorship_sponsor",
        table_name="sponsorship",
        postgresql_where="role = 'Sponsor'",
    )
    op.drop_index("idx_sponsorship_legislator", table_name="sponsorship")
    op.drop_index("idx_sponsorship_law", table_name="sponsorship")
    op.drop_index("idx_sponsorship_bill", table_name="sponsorship")
    op.drop_table("sponsorship")
    op.drop_index("idx_parsing_session_status", table_name="parsing_session")
    op.drop_index("idx_parsing_session_started", table_name="parsing_session")
    op.drop_index("idx_parsing_session_mode", table_name="parsing_session")
    op.drop_index("idx_parsing_session_law", table_name="parsing_session")
    op.drop_table("parsing_session")
    op.drop_index("idx_law_president", table_name="public_law")
    op.drop_index("idx_law_popular_name", table_name="public_law")
    op.drop_index("idx_law_number", table_name="public_law")
    op.drop_index("idx_law_enacted", table_name="public_law")
    op.drop_index("idx_law_effective", table_name="public_law")
    op.drop_index("idx_law_congress", table_name="public_law")
    op.drop_table("public_law")
    op.drop_index("idx_term_legislator", table_name="legislator_term")
    op.drop_index("idx_term_dates", table_name="legislator_term")
    op.drop_index("idx_term_congress", table_name="legislator_term")
    op.drop_table("legislator_term")
    op.drop_index("idx_assignment_committee", table_name="bill_committee_assignment")
    op.drop_index("idx_assignment_bill", table_name="bill_committee_assignment")
    op.drop_table("bill_committee_assignment")
    op.drop_index("idx_amendment_congress", table_name="amendment")
    op.drop_index("idx_amendment_bill", table_name="amendment")
    op.drop_table("amendment")
    op.drop_index("idx_section_group_type", table_name="section_group")
    op.drop_index("idx_section_group_sort", table_name="section_group")
    op.drop_index("idx_section_group_parent", table_name="section_group")
    op.drop_table("section_group")
    op.drop_index("idx_legislator_state", table_name="legislator")
    op.drop_index("idx_legislator_party", table_name="legislator")
    op.drop_index(
        "idx_legislator_current",
        table_name="legislator",
        postgresql_where="is_current_member = TRUE",
    )
    op.drop_table("legislator")
    op.drop_index("idx_ingestion_status", table_name="data_ingestion_log")
    op.drop_index("idx_ingestion_started", table_name="data_ingestion_log")
    op.drop_index("idx_ingestion_source", table_name="data_ingestion_log")
    op.drop_table("data_ingestion_log")
    op.drop_index("idx_correction_table", table_name="data_correction")
    op.drop_index("idx_correction_record", table_name="data_correction")
    op.drop_index("idx_correction_date", table_name="data_correction")
    op.drop_table("data_correction")
    op.drop_index("idx_committee_chamber", table_name="committee")
    op.drop_table("committee")
    op.drop_index("idx_bill_status", table_name="bill")
    op.drop_index(
        "idx_bill_pending",
        table_name="bill",
        postgresql_where="status NOT IN ('Became_Law', 'Failed', 'Vetoed', 'Died_in_Committee')",
    )
    op.drop_index("idx_bill_congress", table_name="bill")
    op.drop_table("bill")

    # Drop all PostgreSQL enum types created by this migration
    for enum_name in [
        "amendment_review_status",
        "bill_status",
        "bill_type",
        "chamber",
        "change_type",
        "law_type",
        "parsing_mode",
        "parsing_session_status",
        "pattern_discovery_status",
        "political_party",
        "reference_type",
        "span_type",
        "sponsorship_role",
        "verification_method",
        "verification_result",
        "vote_type",
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
